name: auto deploy # workflow name

on:
  push: 
    branches:
      - master
jobs:
  build: # job1 id
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    steps:
    - name: Checkout # step1 获取源码
      uses: actions/checkout@v2 # 使用 actions/checkout@v2
      with: # 条件
        submodules: true # Checkout private submodules(themes or something else). 当有子模块时切换分支？
    - name: Setup Node.js 16.x
      uses: actions/setup-node@master
      with:
        node-version: "16.x"
    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
    - name: Generate Public Files
      run: |
        ls source/_posts
        npm i
        npm install hexo-cli -g
        hexo clean && hexo generate
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        external_repository: RinChanNOWWW/rinchannowww.github.io
        publish_branch: gh-pages
        publish_dir: ./public
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
